#
# setup exicutable file name
#
EXE := main.exe

# setup control
#
#DEBUG = TRUE
TOP     := $(shell pwd)
OBJ     := $(TOP)/obj
BIN     := $(TOP)/bin
SRC     := $(TOP)/src
INCLUDE  := $(TOP)/include

ROOTCFLAGS    = $(shell root-config --cflags)
ROOTLIBS      = $(shell root-config --libs)
ROOTGLIBS     = $(shell root-config --glibs)

INCFLAGS = -I$(ROOTSYS)/include
LDFLAGS = -L$(ROOTSYS)/lib

#	
# set up compilers
#	
CPP     = g++

# choose correct CPPFLAGS

#CPPFLAGS = -O -Wall -fPIC -I$(INCLUDE)
CPPFLAGS = -O -Wall -fPIC -I$(INCLUDE) -I$(ROOTCFLAGS) $(INCFLAGS) $(LDFLAGS)
#CPPFLAGS = -O -Wall -fPIC -I$(INCLUDE) -I$(ROOTCFLAGS)
#CPPFLAGS = -Wall -ansi -pedantic -Wno-long-long -I$(INCLUDE) -I$(ROOTCFLAGS) -I. $(LCIOINCLUDES) -D_REENTRANT

CPPLIBS = $(ROOTLIBS) $(ROOTGLIBS)

ifeq ($(DEBUG), TRUE)
CPPFLAGS += -g
endif

ifeq ($(PURIFY), TRUE)
LD = purify $(CPP)
else
LD     = $(CPP)
endif


############## Make Executables ####################################
all: $(EXE)

$(EXE): $(patsubst $(SRC)/%.C,$(OBJ)/%.o,$(wildcard $(SRC)/*.C))
	$(LD) $^ $(CPPLIBS) -o $(BIN)/$(notdir $@)
	@echo

######################################################
$(OBJ)/%.o : 	$(SRC)/%.C
	$(CPP)  $(CPPFLAGS) -c $(SRC)/$(notdir $<) -o $(OBJ)/$(notdir $@)
	@echo	

.PHONY:clean
clean:
	@rm -f $(OBJ)/*.o 
#	@rm -f $(BIN)*


