#
#  This file permits to customize, with commands,
# the menu bar of the G4UIXm, G4UIQt, G4UIWin32 sessions.
# It has no effect with G4UIterminal.


#________________________________________________________ Gui menu
####    File :
/gui/addMenu g4file G4File

/gui/addButton g4file Continue continue
/gui/addButton g4file Exit "exit"


####    Run menu :
/gui/addMenu run Run

/gui/addButton run "beamOn 1" "/run/beamOn 1"
/gui/addButton run run1 "/control/execute ./mac/runFile/run1.mac"       #user file: run1.mac
/gui/addButton run run2 "/control/execute ./mac/runFile/run2.mac"


####    GPS menu :
/gui/addMenu gps GPS

/gui/addButton gps "50 MeV"  "/gps/energy 50 MeV"
/gui/addButton gps "1 GeV"   "/gps/energy 1 GeV"
/gui/addButton gps "10 GeV"  "/gps/energy 10 GeV"
/gui/addButton gps "100 GeV" "/gps/energy 100 GeV"
/gui/addButton gps "1 TeV"   "/gps/energy 1 TeV"
/gui/addButton gps "10 TeV"  "/gps/energy 10 TeV"
/gui/addButton gps "e-"      "/gps/particle e-"
/gui/addButton gps "pi0"     "/gps/particle pi0"
/gui/addButton gps "pi+"     "/gps/particle pi+"
/gui/addButton gps "mu-"     "/gps/particle mu-"
/gui/addButton gps "neutron" "/gps/particle neutron"
/gui/addButton gps "proton"  "/gps/particle proton"


####    Viewer menu :
/gui/addMenu viewer Viewer

/gui/addButton viewer "Refresh viewer" "/vis/viewer/refresh"
/gui/addButton viewer "Update viewer (interaction or end-of-file)" "/vis/viewer/update"
/gui/addButton viewer "Update scene" "/vis/scene/notifyHandlers"
/gui/addButton viewer "Flush viewer (= refresh + update)" "/vis/viewer/flush"
/gui/addButton viewer "Set style surface" "/vis/viewer/set/style surface"
/gui/addButton viewer "Set style wireframe" "/vis/viewer/set/style wire"


#________________________________________________________ Gui icon
####    Add an icon toolbar
/control/execute ./mac/visFile/icons.mac


#________________________________________________________ Gui menu (user special)
####    user file for current project
/control/execute ./mac/userFile/userSpecial.mac


